---
# Secret: 阿里云 DNS API 凭证
# 请先创建此 Secret：kubectl create secret generic alicloud-dns-secret \
#   --from-literal=access-key-id=YOUR_ACCESS_KEY_ID \
#   --from-literal=access-key-secret=YOUR_ACCESS_KEY_SECRET
# 或者取消下面的注释并填入您的凭证
# apiVersion: v1
# kind: Secret
# metadata:
#   name: alicloud-dns-secret
#   namespace: default
# type: Opaque
# stringData:
#   access-key-id: "YOUR_ALICLOUD_ACCESS_KEY_ID"
#   access-key-secret: "YOUR_ALICLOUD_ACCESS_KEY_SECRET"

---
# ServiceAccount for Caddy K8s Router
apiVersion: v1
kind: ServiceAccount
metadata:
  name: caddy-k8s
  namespace: default

---
# ClusterRole: 定义 Caddy 需要的权限
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: caddy-k8s-reader
rules:
  # 读取 Deployments
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "patch"]

  # 读取 Pods（用于查询 Pod IP）
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]

---
# ClusterRoleBinding: 绑定权限到 ServiceAccount
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: caddy-k8s-reader-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: caddy-k8s-reader
subjects:
  - kind: ServiceAccount
    name: caddy-k8s
    namespace: default

---
# ConfigMap: Caddyfile 配置
apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-config
  namespace: default
data:
  Caddyfile: |
    # ============================================================================
    # 生产环境 HTTPS 配置
    # ============================================================================
    #
    # 方案 1：使用 DNS-01 challenge（推荐用于通配符证书）
    # 需要编译 DNS 提供商插件，例如：
    # xcaddy build --with github.com/ysicing/caddy2-gitspace=. \
    #              --with github.com/caddy-dns/alidns
    #
    # 方案 2：使用 HTTP-01 challenge（适用于单个域名）
    # k8s_router 会为每个 Deployment 动态注入路由，Caddy 会自动为每个域名申请证书
    # 不需要额外的 DNS 插件，但不支持通配符证书
    # ============================================================================

    {
      admin localhost:2019
      persist_config off
      log {
        output stdout
        format json
        level INFO
      }

      # 邮箱用于 ACME 证书申请
      email {$ACME_EMAIL:admin@example.com}

      # K8s Router 全局配置
      k8s_router {
        namespace {$K8S_NAMESPACE}
        base_domain {$BASE_DOMAIN}
        default_port {$DEFAULT_PORT}
      }
    }

    # ============================================================================
    # 方案 1：通配符域名 + DNS-01 challenge（需要 DNS 插件）
    # ============================================================================
    # 取消下面的注释以启用（同时注释掉方案 2）
    #
    # *.{$BASE_DOMAIN} {
    #   # TLS 配置 - 使用 DNS-01 challenge（阿里云 DNS）
    #   tls {
    #     dns alidns {
    #       access_key_id {$ALICLOUD_ACCESS_KEY}
    #       access_key_secret {$ALICLOUD_SECRET_KEY}
    #     }
    #   }
    #
    #   handle /healthz {
    #     respond "OK" 200
    #   }
    #
    #   # 默认响应（当没有匹配的动态路由时）
    #   respond "Caddy K8s Router - No matching deployment" 404
    #
    #   log {
    #     output stdout
    #     format json
    #   }
    # }
    #
    # # HTTP 到 HTTPS 重定向
    # http://*.{$BASE_DOMAIN} {
    #   redir https://{host}{uri} permanent
    # }

    # ============================================================================
    # 方案 2：动态域名 + HTTP-01 challenge（默认，无需额外插件）
    # ============================================================================
    # k8s_router 注入的路由会自动启用 HTTPS（使用 HTTP-01 challenge）
    # 这里只需要定义通配符站点作为兜底

    *.{$BASE_DOMAIN} {
      handle /healthz {
        respond "OK" 200
      }

      # 默认响应（当没有匹配的动态路由时）
      respond "Caddy K8s Router - No matching deployment" 404

      log {
        output stdout
        format json
      }
    }

    # HTTP 到 HTTPS 重定向（Caddy 会自动处理）
    http://*.{$BASE_DOMAIN} {
      redir https://{host}{uri} permanent
    }

---
# Deployment: Caddy K8s Router
apiVersion: apps/v1
kind: Deployment
metadata:
  name: caddy-k8s
  namespace: default
  labels:
    app: caddy-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caddy-k8s
  template:
    metadata:
      labels:
        app: caddy-k8s
    spec:
      serviceAccountName: caddy-k8s
      containers:
        - name: caddy
          # 使用包含 k8s_router 插件的 Caddy 镜像
          image: your-registry/caddy-k8s:latest
          imagePullPolicy: Always

          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: admin
              containerPort: 2019
              protocol: TCP

          env:
            # K8s 命名空间（监听的命名空间）
            - name: K8S_NAMESPACE
              value: "default"

            # 基础域名
            - name: BASE_DOMAIN
              value: "example.com"

            # 默认端口
            - name: DEFAULT_PORT
              value: "8089"

            # 阿里云 DNS API 配置（用于 TLS DNS-01 验证）
            - name: ALICLOUD_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: alicloud-dns-secret
                  key: access-key-id

            - name: ALICLOUD_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: alicloud-dns-secret
                  key: access-key-secret

          volumeMounts:
            - name: config
              mountPath: /etc/caddy
              readOnly: true

          # 健康检查（使用 HTTPS）
          livenessProbe:
            httpGet:
              path: /healthz
              port: 443
              scheme: HTTPS
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /healthz
              port: 443
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 2

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi

      volumes:
        - name: config
          configMap:
            name: caddy-config

---
# Service: 使用阿里云 SLB 负载均衡
apiVersion: v1
kind: Service
metadata:
  name: caddy-k8s
  namespace: default
  labels:
    app: caddy-k8s
  annotations:
    # 阿里云 SLB 配置
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-spec: "slb.s1.small"  # SLB 规格
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-charge-type: "paybytraffic"  # 按流量计费
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-address-type: "internet"  # 公网 SLB

    # 可选：健康检查配置
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-health-check-flag: "on"
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-health-check-type: "tcp"
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-health-check-connect-timeout: "5"
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-healthy-threshold: "2"
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-unhealthy-threshold: "2"
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-health-check-interval: "2"

    # 可选：使用已有 SLB（取消注释并填入 SLB ID）
    # service.beta.kubernetes.io/alibaba-cloud-loadbalancer-id: "lb-xxxxxxxxxx"

    # 可选：会话保持
    # service.beta.kubernetes.io/alibaba-cloud-loadbalancer-persistence-timeout: "1800"
spec:
  type: LoadBalancer
  selector:
    app: caddy-k8s
  ports:
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP

    - name: http
      port: 80
      targetPort: 80
      protocol: TCP

