---
# ServiceAccount for Caddy K8s Router
apiVersion: v1
kind: ServiceAccount
metadata:
  name: caddy-k8s
  namespace: gaeaflow-spaces
---
# ClusterRole: 定义 Caddy 需要的权限
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: caddy-k8s-reader
rules:
  # 读取 Deployments
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "patch"]

  # 读取 Pods（用于查询 Pod IP）
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]

---
# ClusterRoleBinding: 绑定权限到 ServiceAccount
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: caddy-k8s-reader-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: caddy-k8s-reader
subjects:
  - kind: ServiceAccount
    name: caddy-k8s
    namespace: gaeaflow-spaces
---
# ConfigMap: Caddyfile 配置（本地测试 - HTTP only）
apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-config-local
  namespace: gaeaflow-spaces
data:
  Caddyfile: |
    {
      admin localhost:2019
      auto_https off
      log {
        output stdout
        format json
        level DEBUG
      }

      k8s_router {
        namespace {$K8S_NAMESPACE}
        base_domain {$BASE_DOMAIN}
        default_port {$DEFAULT_PORT}
      }
    }

    *.{$BASE_DOMAIN} {
      handle /healthz {
        respond "OK" 200
      }

      # 默认响应（当没有匹配的动态路由时）
      respond "Caddy K8s Router - No matching deployment" 404

      log {
        output stdout
        format json
      }
    }

---
# Deployment: Caddy K8s Router (本地测试版)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: caddy-k8s-local
  namespace: gaeaflow-spaces
  labels:
    app: caddy-k8s-local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caddy-k8s-local
  template:
    metadata:
      labels:
        app: caddy-k8s-local
    spec:
      serviceAccountName: caddy-k8s
      containers:
        - name: caddy
          # 使用本地构建的镜像
          image: ysicing/caddy
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: admin
              containerPort: 2019
              protocol: TCP

          env:
            # K8s 命名空间
            - name: K8S_NAMESPACE
              value: "gaeaflow-spaces"

            # 基础域名（本地测试使用 localhost 或 .local）
            - name: BASE_DOMAIN
              value: "flow.talkdev.webpod.eu.org"

            # 默认端口
            - name: DEFAULT_PORT
              value: "8089"

          volumeMounts:
            - name: config
              mountPath: /etc/caddy
              readOnly: true

          # 健康检查（HTTP）
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 2

          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi

      volumes:
        - name: config
          configMap:
            name: caddy-config-local

---
# Service: NodePort（本地测试）
apiVersion: v1
kind: Service
metadata:
  name: caddy-k8s-local
  namespace: gaeaflow-spaces
  labels:
    app: caddy-k8s-local
spec:
  type: NodePort
  selector:
    app: caddy-k8s-local
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
